### ISSUE TITLE
KeyError: href

### ISSUE THREAD

**Issue by Mastersam07** [LordGhostX/docs-to-md-cli#1]
I am getting some key error while using this utility.

#### Process
I published my article to the web and passed it as stated in the docs, with the URL in quotes and without quotes. Same issue.

![image](https://user-images.githubusercontent.com/31275429/104528130-459b8f00-55bb-11eb-8f43-39b9044db2e5.png)

Probably I am doing something wrong. How do I go about this?

**Comment by LordGhostX** [comment]
Send me the link you're trying to scrape so I can recreate it on my personal computer

**Comment by Mastersam07** [comment]
This issue has been fixed by this [commit](https://github.com/LordGhostX/docs-to-md-cli/commit/be967329ec5082b14c5a38fdb59fc1bdb14fb63c).

**Comment by Mastersam07** [comment]
Closing this.
